version: '3'

services:
  nodejs:
    build:
      context: .
      dockerfile: Dockerfile
    image: nodejs
    container_name: nodejs
    restart: unless-stopped
    ports:
      - "80:8080"
    volumes:
      - .:/home/node/app
      - node_modules:/home/node/app/node_modules
    networks:
      - app-network
    command: sh -c "npm install && npm start"

  mysql-db:
    image: mysql:5.7
    container_name: mysql-db
    env_file: .env
    volumes:
      - ./run/var:/var/lib/mysql
      - ./mysqlconf:/etc/mysql/conf.d
    environment:
      - MYSQL_ROOT_HOST=$MYSQL_ROOT_HOST
      - MYSQL_ROOT_PASSWORD=$MYSQL_ROOT_PASSWORD
      - MYSQL_DATABASE=$MYSQL_DATABASE
      - MYSQL_USER=$MYSQL_USERNAME
      - MYSQL_PASSWORD=$MYSQL_PASSWORD
      - MYSQL_ALLOW_EMPTY_PASSWORD=true
      - MYSQL_RANDOM_ROOT_PASSWORD=true
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  node_modules:
